
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Naloga` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Naloga
 * 
 */
export type NalogaModel = runtime.Types.Result.DefaultSelection<Prisma.$NalogaPayload>

export type AggregateNaloga = {
  _count: NalogaCountAggregateOutputType | null
  _avg: NalogaAvgAggregateOutputType | null
  _sum: NalogaSumAggregateOutputType | null
  _min: NalogaMinAggregateOutputType | null
  _max: NalogaMaxAggregateOutputType | null
}

export type NalogaAvgAggregateOutputType = {
  cena: number | null
}

export type NalogaSumAggregateOutputType = {
  cena: number | null
}

export type NalogaMinAggregateOutputType = {
  id: string | null
  naslov: string | null
  opis: string | null
  cena: number | null
  kategorija: string | null
  status: string | null
  createdAt: Date | null
  narocnikId: string | null
}

export type NalogaMaxAggregateOutputType = {
  id: string | null
  naslov: string | null
  opis: string | null
  cena: number | null
  kategorija: string | null
  status: string | null
  createdAt: Date | null
  narocnikId: string | null
}

export type NalogaCountAggregateOutputType = {
  id: number
  naslov: number
  opis: number
  cena: number
  kategorija: number
  status: number
  createdAt: number
  narocnikId: number
  _all: number
}


export type NalogaAvgAggregateInputType = {
  cena?: true
}

export type NalogaSumAggregateInputType = {
  cena?: true
}

export type NalogaMinAggregateInputType = {
  id?: true
  naslov?: true
  opis?: true
  cena?: true
  kategorija?: true
  status?: true
  createdAt?: true
  narocnikId?: true
}

export type NalogaMaxAggregateInputType = {
  id?: true
  naslov?: true
  opis?: true
  cena?: true
  kategorija?: true
  status?: true
  createdAt?: true
  narocnikId?: true
}

export type NalogaCountAggregateInputType = {
  id?: true
  naslov?: true
  opis?: true
  cena?: true
  kategorija?: true
  status?: true
  createdAt?: true
  narocnikId?: true
  _all?: true
}

export type NalogaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Naloga to aggregate.
   */
  where?: Prisma.NalogaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Nalogas to fetch.
   */
  orderBy?: Prisma.NalogaOrderByWithRelationInput | Prisma.NalogaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NalogaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Nalogas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Nalogas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Nalogas
  **/
  _count?: true | NalogaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: NalogaAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: NalogaSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NalogaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NalogaMaxAggregateInputType
}

export type GetNalogaAggregateType<T extends NalogaAggregateArgs> = {
      [P in keyof T & keyof AggregateNaloga]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNaloga[P]>
    : Prisma.GetScalarType<T[P], AggregateNaloga[P]>
}




export type NalogaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NalogaWhereInput
  orderBy?: Prisma.NalogaOrderByWithAggregationInput | Prisma.NalogaOrderByWithAggregationInput[]
  by: Prisma.NalogaScalarFieldEnum[] | Prisma.NalogaScalarFieldEnum
  having?: Prisma.NalogaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NalogaCountAggregateInputType | true
  _avg?: NalogaAvgAggregateInputType
  _sum?: NalogaSumAggregateInputType
  _min?: NalogaMinAggregateInputType
  _max?: NalogaMaxAggregateInputType
}

export type NalogaGroupByOutputType = {
  id: string
  naslov: string
  opis: string
  cena: number
  kategorija: string
  status: string
  createdAt: Date
  narocnikId: string
  _count: NalogaCountAggregateOutputType | null
  _avg: NalogaAvgAggregateOutputType | null
  _sum: NalogaSumAggregateOutputType | null
  _min: NalogaMinAggregateOutputType | null
  _max: NalogaMaxAggregateOutputType | null
}

export type GetNalogaGroupByPayload<T extends NalogaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NalogaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NalogaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NalogaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NalogaGroupByOutputType[P]>
      }
    >
  >



export type NalogaWhereInput = {
  AND?: Prisma.NalogaWhereInput | Prisma.NalogaWhereInput[]
  OR?: Prisma.NalogaWhereInput[]
  NOT?: Prisma.NalogaWhereInput | Prisma.NalogaWhereInput[]
  id?: Prisma.StringFilter<"Naloga"> | string
  naslov?: Prisma.StringFilter<"Naloga"> | string
  opis?: Prisma.StringFilter<"Naloga"> | string
  cena?: Prisma.FloatFilter<"Naloga"> | number
  kategorija?: Prisma.StringFilter<"Naloga"> | string
  status?: Prisma.StringFilter<"Naloga"> | string
  createdAt?: Prisma.DateTimeFilter<"Naloga"> | Date | string
  narocnikId?: Prisma.StringFilter<"Naloga"> | string
  narocnik?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type NalogaOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  naslov?: Prisma.SortOrder
  opis?: Prisma.SortOrder
  cena?: Prisma.SortOrder
  kategorija?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  narocnikId?: Prisma.SortOrder
  narocnik?: Prisma.UserOrderByWithRelationInput
}

export type NalogaWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.NalogaWhereInput | Prisma.NalogaWhereInput[]
  OR?: Prisma.NalogaWhereInput[]
  NOT?: Prisma.NalogaWhereInput | Prisma.NalogaWhereInput[]
  naslov?: Prisma.StringFilter<"Naloga"> | string
  opis?: Prisma.StringFilter<"Naloga"> | string
  cena?: Prisma.FloatFilter<"Naloga"> | number
  kategorija?: Prisma.StringFilter<"Naloga"> | string
  status?: Prisma.StringFilter<"Naloga"> | string
  createdAt?: Prisma.DateTimeFilter<"Naloga"> | Date | string
  narocnikId?: Prisma.StringFilter<"Naloga"> | string
  narocnik?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type NalogaOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  naslov?: Prisma.SortOrder
  opis?: Prisma.SortOrder
  cena?: Prisma.SortOrder
  kategorija?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  narocnikId?: Prisma.SortOrder
  _count?: Prisma.NalogaCountOrderByAggregateInput
  _avg?: Prisma.NalogaAvgOrderByAggregateInput
  _max?: Prisma.NalogaMaxOrderByAggregateInput
  _min?: Prisma.NalogaMinOrderByAggregateInput
  _sum?: Prisma.NalogaSumOrderByAggregateInput
}

export type NalogaScalarWhereWithAggregatesInput = {
  AND?: Prisma.NalogaScalarWhereWithAggregatesInput | Prisma.NalogaScalarWhereWithAggregatesInput[]
  OR?: Prisma.NalogaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NalogaScalarWhereWithAggregatesInput | Prisma.NalogaScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Naloga"> | string
  naslov?: Prisma.StringWithAggregatesFilter<"Naloga"> | string
  opis?: Prisma.StringWithAggregatesFilter<"Naloga"> | string
  cena?: Prisma.FloatWithAggregatesFilter<"Naloga"> | number
  kategorija?: Prisma.StringWithAggregatesFilter<"Naloga"> | string
  status?: Prisma.StringWithAggregatesFilter<"Naloga"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Naloga"> | Date | string
  narocnikId?: Prisma.StringWithAggregatesFilter<"Naloga"> | string
}

export type NalogaCreateInput = {
  id?: string
  naslov: string
  opis: string
  cena: number
  kategorija: string
  status?: string
  createdAt?: Date | string
  narocnik: Prisma.UserCreateNestedOneWithoutNalogeInput
}

export type NalogaUncheckedCreateInput = {
  id?: string
  naslov: string
  opis: string
  cena: number
  kategorija: string
  status?: string
  createdAt?: Date | string
  narocnikId: string
}

export type NalogaUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  opis?: Prisma.StringFieldUpdateOperationsInput | string
  cena?: Prisma.FloatFieldUpdateOperationsInput | number
  kategorija?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  narocnik?: Prisma.UserUpdateOneRequiredWithoutNalogeNestedInput
}

export type NalogaUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  opis?: Prisma.StringFieldUpdateOperationsInput | string
  cena?: Prisma.FloatFieldUpdateOperationsInput | number
  kategorija?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  narocnikId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type NalogaCreateManyInput = {
  id?: string
  naslov: string
  opis: string
  cena: number
  kategorija: string
  status?: string
  createdAt?: Date | string
  narocnikId: string
}

export type NalogaUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  opis?: Prisma.StringFieldUpdateOperationsInput | string
  cena?: Prisma.FloatFieldUpdateOperationsInput | number
  kategorija?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NalogaUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  opis?: Prisma.StringFieldUpdateOperationsInput | string
  cena?: Prisma.FloatFieldUpdateOperationsInput | number
  kategorija?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  narocnikId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type NalogaListRelationFilter = {
  every?: Prisma.NalogaWhereInput
  some?: Prisma.NalogaWhereInput
  none?: Prisma.NalogaWhereInput
}

export type NalogaOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NalogaCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  naslov?: Prisma.SortOrder
  opis?: Prisma.SortOrder
  cena?: Prisma.SortOrder
  kategorija?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  narocnikId?: Prisma.SortOrder
}

export type NalogaAvgOrderByAggregateInput = {
  cena?: Prisma.SortOrder
}

export type NalogaMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  naslov?: Prisma.SortOrder
  opis?: Prisma.SortOrder
  cena?: Prisma.SortOrder
  kategorija?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  narocnikId?: Prisma.SortOrder
}

export type NalogaMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  naslov?: Prisma.SortOrder
  opis?: Prisma.SortOrder
  cena?: Prisma.SortOrder
  kategorija?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  narocnikId?: Prisma.SortOrder
}

export type NalogaSumOrderByAggregateInput = {
  cena?: Prisma.SortOrder
}

export type NalogaCreateNestedManyWithoutNarocnikInput = {
  create?: Prisma.XOR<Prisma.NalogaCreateWithoutNarocnikInput, Prisma.NalogaUncheckedCreateWithoutNarocnikInput> | Prisma.NalogaCreateWithoutNarocnikInput[] | Prisma.NalogaUncheckedCreateWithoutNarocnikInput[]
  connectOrCreate?: Prisma.NalogaCreateOrConnectWithoutNarocnikInput | Prisma.NalogaCreateOrConnectWithoutNarocnikInput[]
  createMany?: Prisma.NalogaCreateManyNarocnikInputEnvelope
  connect?: Prisma.NalogaWhereUniqueInput | Prisma.NalogaWhereUniqueInput[]
}

export type NalogaUncheckedCreateNestedManyWithoutNarocnikInput = {
  create?: Prisma.XOR<Prisma.NalogaCreateWithoutNarocnikInput, Prisma.NalogaUncheckedCreateWithoutNarocnikInput> | Prisma.NalogaCreateWithoutNarocnikInput[] | Prisma.NalogaUncheckedCreateWithoutNarocnikInput[]
  connectOrCreate?: Prisma.NalogaCreateOrConnectWithoutNarocnikInput | Prisma.NalogaCreateOrConnectWithoutNarocnikInput[]
  createMany?: Prisma.NalogaCreateManyNarocnikInputEnvelope
  connect?: Prisma.NalogaWhereUniqueInput | Prisma.NalogaWhereUniqueInput[]
}

export type NalogaUpdateManyWithoutNarocnikNestedInput = {
  create?: Prisma.XOR<Prisma.NalogaCreateWithoutNarocnikInput, Prisma.NalogaUncheckedCreateWithoutNarocnikInput> | Prisma.NalogaCreateWithoutNarocnikInput[] | Prisma.NalogaUncheckedCreateWithoutNarocnikInput[]
  connectOrCreate?: Prisma.NalogaCreateOrConnectWithoutNarocnikInput | Prisma.NalogaCreateOrConnectWithoutNarocnikInput[]
  upsert?: Prisma.NalogaUpsertWithWhereUniqueWithoutNarocnikInput | Prisma.NalogaUpsertWithWhereUniqueWithoutNarocnikInput[]
  createMany?: Prisma.NalogaCreateManyNarocnikInputEnvelope
  set?: Prisma.NalogaWhereUniqueInput | Prisma.NalogaWhereUniqueInput[]
  disconnect?: Prisma.NalogaWhereUniqueInput | Prisma.NalogaWhereUniqueInput[]
  delete?: Prisma.NalogaWhereUniqueInput | Prisma.NalogaWhereUniqueInput[]
  connect?: Prisma.NalogaWhereUniqueInput | Prisma.NalogaWhereUniqueInput[]
  update?: Prisma.NalogaUpdateWithWhereUniqueWithoutNarocnikInput | Prisma.NalogaUpdateWithWhereUniqueWithoutNarocnikInput[]
  updateMany?: Prisma.NalogaUpdateManyWithWhereWithoutNarocnikInput | Prisma.NalogaUpdateManyWithWhereWithoutNarocnikInput[]
  deleteMany?: Prisma.NalogaScalarWhereInput | Prisma.NalogaScalarWhereInput[]
}

export type NalogaUncheckedUpdateManyWithoutNarocnikNestedInput = {
  create?: Prisma.XOR<Prisma.NalogaCreateWithoutNarocnikInput, Prisma.NalogaUncheckedCreateWithoutNarocnikInput> | Prisma.NalogaCreateWithoutNarocnikInput[] | Prisma.NalogaUncheckedCreateWithoutNarocnikInput[]
  connectOrCreate?: Prisma.NalogaCreateOrConnectWithoutNarocnikInput | Prisma.NalogaCreateOrConnectWithoutNarocnikInput[]
  upsert?: Prisma.NalogaUpsertWithWhereUniqueWithoutNarocnikInput | Prisma.NalogaUpsertWithWhereUniqueWithoutNarocnikInput[]
  createMany?: Prisma.NalogaCreateManyNarocnikInputEnvelope
  set?: Prisma.NalogaWhereUniqueInput | Prisma.NalogaWhereUniqueInput[]
  disconnect?: Prisma.NalogaWhereUniqueInput | Prisma.NalogaWhereUniqueInput[]
  delete?: Prisma.NalogaWhereUniqueInput | Prisma.NalogaWhereUniqueInput[]
  connect?: Prisma.NalogaWhereUniqueInput | Prisma.NalogaWhereUniqueInput[]
  update?: Prisma.NalogaUpdateWithWhereUniqueWithoutNarocnikInput | Prisma.NalogaUpdateWithWhereUniqueWithoutNarocnikInput[]
  updateMany?: Prisma.NalogaUpdateManyWithWhereWithoutNarocnikInput | Prisma.NalogaUpdateManyWithWhereWithoutNarocnikInput[]
  deleteMany?: Prisma.NalogaScalarWhereInput | Prisma.NalogaScalarWhereInput[]
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NalogaCreateWithoutNarocnikInput = {
  id?: string
  naslov: string
  opis: string
  cena: number
  kategorija: string
  status?: string
  createdAt?: Date | string
}

export type NalogaUncheckedCreateWithoutNarocnikInput = {
  id?: string
  naslov: string
  opis: string
  cena: number
  kategorija: string
  status?: string
  createdAt?: Date | string
}

export type NalogaCreateOrConnectWithoutNarocnikInput = {
  where: Prisma.NalogaWhereUniqueInput
  create: Prisma.XOR<Prisma.NalogaCreateWithoutNarocnikInput, Prisma.NalogaUncheckedCreateWithoutNarocnikInput>
}

export type NalogaCreateManyNarocnikInputEnvelope = {
  data: Prisma.NalogaCreateManyNarocnikInput | Prisma.NalogaCreateManyNarocnikInput[]
  skipDuplicates?: boolean
}

export type NalogaUpsertWithWhereUniqueWithoutNarocnikInput = {
  where: Prisma.NalogaWhereUniqueInput
  update: Prisma.XOR<Prisma.NalogaUpdateWithoutNarocnikInput, Prisma.NalogaUncheckedUpdateWithoutNarocnikInput>
  create: Prisma.XOR<Prisma.NalogaCreateWithoutNarocnikInput, Prisma.NalogaUncheckedCreateWithoutNarocnikInput>
}

export type NalogaUpdateWithWhereUniqueWithoutNarocnikInput = {
  where: Prisma.NalogaWhereUniqueInput
  data: Prisma.XOR<Prisma.NalogaUpdateWithoutNarocnikInput, Prisma.NalogaUncheckedUpdateWithoutNarocnikInput>
}

export type NalogaUpdateManyWithWhereWithoutNarocnikInput = {
  where: Prisma.NalogaScalarWhereInput
  data: Prisma.XOR<Prisma.NalogaUpdateManyMutationInput, Prisma.NalogaUncheckedUpdateManyWithoutNarocnikInput>
}

export type NalogaScalarWhereInput = {
  AND?: Prisma.NalogaScalarWhereInput | Prisma.NalogaScalarWhereInput[]
  OR?: Prisma.NalogaScalarWhereInput[]
  NOT?: Prisma.NalogaScalarWhereInput | Prisma.NalogaScalarWhereInput[]
  id?: Prisma.StringFilter<"Naloga"> | string
  naslov?: Prisma.StringFilter<"Naloga"> | string
  opis?: Prisma.StringFilter<"Naloga"> | string
  cena?: Prisma.FloatFilter<"Naloga"> | number
  kategorija?: Prisma.StringFilter<"Naloga"> | string
  status?: Prisma.StringFilter<"Naloga"> | string
  createdAt?: Prisma.DateTimeFilter<"Naloga"> | Date | string
  narocnikId?: Prisma.StringFilter<"Naloga"> | string
}

export type NalogaCreateManyNarocnikInput = {
  id?: string
  naslov: string
  opis: string
  cena: number
  kategorija: string
  status?: string
  createdAt?: Date | string
}

export type NalogaUpdateWithoutNarocnikInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  opis?: Prisma.StringFieldUpdateOperationsInput | string
  cena?: Prisma.FloatFieldUpdateOperationsInput | number
  kategorija?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NalogaUncheckedUpdateWithoutNarocnikInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  opis?: Prisma.StringFieldUpdateOperationsInput | string
  cena?: Prisma.FloatFieldUpdateOperationsInput | number
  kategorija?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NalogaUncheckedUpdateManyWithoutNarocnikInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  naslov?: Prisma.StringFieldUpdateOperationsInput | string
  opis?: Prisma.StringFieldUpdateOperationsInput | string
  cena?: Prisma.FloatFieldUpdateOperationsInput | number
  kategorija?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type NalogaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  naslov?: boolean
  opis?: boolean
  cena?: boolean
  kategorija?: boolean
  status?: boolean
  createdAt?: boolean
  narocnikId?: boolean
  narocnik?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["naloga"]>

export type NalogaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  naslov?: boolean
  opis?: boolean
  cena?: boolean
  kategorija?: boolean
  status?: boolean
  createdAt?: boolean
  narocnikId?: boolean
  narocnik?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["naloga"]>

export type NalogaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  naslov?: boolean
  opis?: boolean
  cena?: boolean
  kategorija?: boolean
  status?: boolean
  createdAt?: boolean
  narocnikId?: boolean
  narocnik?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["naloga"]>

export type NalogaSelectScalar = {
  id?: boolean
  naslov?: boolean
  opis?: boolean
  cena?: boolean
  kategorija?: boolean
  status?: boolean
  createdAt?: boolean
  narocnikId?: boolean
}

export type NalogaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "naslov" | "opis" | "cena" | "kategorija" | "status" | "createdAt" | "narocnikId", ExtArgs["result"]["naloga"]>
export type NalogaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  narocnik?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type NalogaIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  narocnik?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type NalogaIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  narocnik?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $NalogaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Naloga"
  objects: {
    narocnik: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    naslov: string
    opis: string
    cena: number
    kategorija: string
    status: string
    createdAt: Date
    narocnikId: string
  }, ExtArgs["result"]["naloga"]>
  composites: {}
}

export type NalogaGetPayload<S extends boolean | null | undefined | NalogaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NalogaPayload, S>

export type NalogaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NalogaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NalogaCountAggregateInputType | true
  }

export interface NalogaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Naloga'], meta: { name: 'Naloga' } }
  /**
   * Find zero or one Naloga that matches the filter.
   * @param {NalogaFindUniqueArgs} args - Arguments to find a Naloga
   * @example
   * // Get one Naloga
   * const naloga = await prisma.naloga.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NalogaFindUniqueArgs>(args: Prisma.SelectSubset<T, NalogaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NalogaClient<runtime.Types.Result.GetResult<Prisma.$NalogaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Naloga that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NalogaFindUniqueOrThrowArgs} args - Arguments to find a Naloga
   * @example
   * // Get one Naloga
   * const naloga = await prisma.naloga.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NalogaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NalogaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NalogaClient<runtime.Types.Result.GetResult<Prisma.$NalogaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Naloga that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NalogaFindFirstArgs} args - Arguments to find a Naloga
   * @example
   * // Get one Naloga
   * const naloga = await prisma.naloga.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NalogaFindFirstArgs>(args?: Prisma.SelectSubset<T, NalogaFindFirstArgs<ExtArgs>>): Prisma.Prisma__NalogaClient<runtime.Types.Result.GetResult<Prisma.$NalogaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Naloga that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NalogaFindFirstOrThrowArgs} args - Arguments to find a Naloga
   * @example
   * // Get one Naloga
   * const naloga = await prisma.naloga.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NalogaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NalogaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NalogaClient<runtime.Types.Result.GetResult<Prisma.$NalogaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Nalogas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NalogaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Nalogas
   * const nalogas = await prisma.naloga.findMany()
   * 
   * // Get first 10 Nalogas
   * const nalogas = await prisma.naloga.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const nalogaWithIdOnly = await prisma.naloga.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NalogaFindManyArgs>(args?: Prisma.SelectSubset<T, NalogaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NalogaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Naloga.
   * @param {NalogaCreateArgs} args - Arguments to create a Naloga.
   * @example
   * // Create one Naloga
   * const Naloga = await prisma.naloga.create({
   *   data: {
   *     // ... data to create a Naloga
   *   }
   * })
   * 
   */
  create<T extends NalogaCreateArgs>(args: Prisma.SelectSubset<T, NalogaCreateArgs<ExtArgs>>): Prisma.Prisma__NalogaClient<runtime.Types.Result.GetResult<Prisma.$NalogaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Nalogas.
   * @param {NalogaCreateManyArgs} args - Arguments to create many Nalogas.
   * @example
   * // Create many Nalogas
   * const naloga = await prisma.naloga.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NalogaCreateManyArgs>(args?: Prisma.SelectSubset<T, NalogaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Nalogas and returns the data saved in the database.
   * @param {NalogaCreateManyAndReturnArgs} args - Arguments to create many Nalogas.
   * @example
   * // Create many Nalogas
   * const naloga = await prisma.naloga.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Nalogas and only return the `id`
   * const nalogaWithIdOnly = await prisma.naloga.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NalogaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NalogaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NalogaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Naloga.
   * @param {NalogaDeleteArgs} args - Arguments to delete one Naloga.
   * @example
   * // Delete one Naloga
   * const Naloga = await prisma.naloga.delete({
   *   where: {
   *     // ... filter to delete one Naloga
   *   }
   * })
   * 
   */
  delete<T extends NalogaDeleteArgs>(args: Prisma.SelectSubset<T, NalogaDeleteArgs<ExtArgs>>): Prisma.Prisma__NalogaClient<runtime.Types.Result.GetResult<Prisma.$NalogaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Naloga.
   * @param {NalogaUpdateArgs} args - Arguments to update one Naloga.
   * @example
   * // Update one Naloga
   * const naloga = await prisma.naloga.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NalogaUpdateArgs>(args: Prisma.SelectSubset<T, NalogaUpdateArgs<ExtArgs>>): Prisma.Prisma__NalogaClient<runtime.Types.Result.GetResult<Prisma.$NalogaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Nalogas.
   * @param {NalogaDeleteManyArgs} args - Arguments to filter Nalogas to delete.
   * @example
   * // Delete a few Nalogas
   * const { count } = await prisma.naloga.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NalogaDeleteManyArgs>(args?: Prisma.SelectSubset<T, NalogaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Nalogas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NalogaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Nalogas
   * const naloga = await prisma.naloga.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NalogaUpdateManyArgs>(args: Prisma.SelectSubset<T, NalogaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Nalogas and returns the data updated in the database.
   * @param {NalogaUpdateManyAndReturnArgs} args - Arguments to update many Nalogas.
   * @example
   * // Update many Nalogas
   * const naloga = await prisma.naloga.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Nalogas and only return the `id`
   * const nalogaWithIdOnly = await prisma.naloga.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NalogaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NalogaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NalogaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Naloga.
   * @param {NalogaUpsertArgs} args - Arguments to update or create a Naloga.
   * @example
   * // Update or create a Naloga
   * const naloga = await prisma.naloga.upsert({
   *   create: {
   *     // ... data to create a Naloga
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Naloga we want to update
   *   }
   * })
   */
  upsert<T extends NalogaUpsertArgs>(args: Prisma.SelectSubset<T, NalogaUpsertArgs<ExtArgs>>): Prisma.Prisma__NalogaClient<runtime.Types.Result.GetResult<Prisma.$NalogaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Nalogas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NalogaCountArgs} args - Arguments to filter Nalogas to count.
   * @example
   * // Count the number of Nalogas
   * const count = await prisma.naloga.count({
   *   where: {
   *     // ... the filter for the Nalogas we want to count
   *   }
   * })
  **/
  count<T extends NalogaCountArgs>(
    args?: Prisma.Subset<T, NalogaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NalogaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Naloga.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NalogaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NalogaAggregateArgs>(args: Prisma.Subset<T, NalogaAggregateArgs>): Prisma.PrismaPromise<GetNalogaAggregateType<T>>

  /**
   * Group by Naloga.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NalogaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NalogaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NalogaGroupByArgs['orderBy'] }
      : { orderBy?: NalogaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NalogaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNalogaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Naloga model
 */
readonly fields: NalogaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Naloga.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NalogaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  narocnik<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Naloga model
 */
export interface NalogaFieldRefs {
  readonly id: Prisma.FieldRef<"Naloga", 'String'>
  readonly naslov: Prisma.FieldRef<"Naloga", 'String'>
  readonly opis: Prisma.FieldRef<"Naloga", 'String'>
  readonly cena: Prisma.FieldRef<"Naloga", 'Float'>
  readonly kategorija: Prisma.FieldRef<"Naloga", 'String'>
  readonly status: Prisma.FieldRef<"Naloga", 'String'>
  readonly createdAt: Prisma.FieldRef<"Naloga", 'DateTime'>
  readonly narocnikId: Prisma.FieldRef<"Naloga", 'String'>
}
    

// Custom InputTypes
/**
 * Naloga findUnique
 */
export type NalogaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Naloga
   */
  select?: Prisma.NalogaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Naloga
   */
  omit?: Prisma.NalogaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NalogaInclude<ExtArgs> | null
  /**
   * Filter, which Naloga to fetch.
   */
  where: Prisma.NalogaWhereUniqueInput
}

/**
 * Naloga findUniqueOrThrow
 */
export type NalogaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Naloga
   */
  select?: Prisma.NalogaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Naloga
   */
  omit?: Prisma.NalogaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NalogaInclude<ExtArgs> | null
  /**
   * Filter, which Naloga to fetch.
   */
  where: Prisma.NalogaWhereUniqueInput
}

/**
 * Naloga findFirst
 */
export type NalogaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Naloga
   */
  select?: Prisma.NalogaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Naloga
   */
  omit?: Prisma.NalogaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NalogaInclude<ExtArgs> | null
  /**
   * Filter, which Naloga to fetch.
   */
  where?: Prisma.NalogaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Nalogas to fetch.
   */
  orderBy?: Prisma.NalogaOrderByWithRelationInput | Prisma.NalogaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Nalogas.
   */
  cursor?: Prisma.NalogaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Nalogas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Nalogas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Nalogas.
   */
  distinct?: Prisma.NalogaScalarFieldEnum | Prisma.NalogaScalarFieldEnum[]
}

/**
 * Naloga findFirstOrThrow
 */
export type NalogaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Naloga
   */
  select?: Prisma.NalogaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Naloga
   */
  omit?: Prisma.NalogaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NalogaInclude<ExtArgs> | null
  /**
   * Filter, which Naloga to fetch.
   */
  where?: Prisma.NalogaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Nalogas to fetch.
   */
  orderBy?: Prisma.NalogaOrderByWithRelationInput | Prisma.NalogaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Nalogas.
   */
  cursor?: Prisma.NalogaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Nalogas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Nalogas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Nalogas.
   */
  distinct?: Prisma.NalogaScalarFieldEnum | Prisma.NalogaScalarFieldEnum[]
}

/**
 * Naloga findMany
 */
export type NalogaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Naloga
   */
  select?: Prisma.NalogaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Naloga
   */
  omit?: Prisma.NalogaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NalogaInclude<ExtArgs> | null
  /**
   * Filter, which Nalogas to fetch.
   */
  where?: Prisma.NalogaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Nalogas to fetch.
   */
  orderBy?: Prisma.NalogaOrderByWithRelationInput | Prisma.NalogaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Nalogas.
   */
  cursor?: Prisma.NalogaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Nalogas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Nalogas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Nalogas.
   */
  distinct?: Prisma.NalogaScalarFieldEnum | Prisma.NalogaScalarFieldEnum[]
}

/**
 * Naloga create
 */
export type NalogaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Naloga
   */
  select?: Prisma.NalogaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Naloga
   */
  omit?: Prisma.NalogaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NalogaInclude<ExtArgs> | null
  /**
   * The data needed to create a Naloga.
   */
  data: Prisma.XOR<Prisma.NalogaCreateInput, Prisma.NalogaUncheckedCreateInput>
}

/**
 * Naloga createMany
 */
export type NalogaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Nalogas.
   */
  data: Prisma.NalogaCreateManyInput | Prisma.NalogaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Naloga createManyAndReturn
 */
export type NalogaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Naloga
   */
  select?: Prisma.NalogaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Naloga
   */
  omit?: Prisma.NalogaOmit<ExtArgs> | null
  /**
   * The data used to create many Nalogas.
   */
  data: Prisma.NalogaCreateManyInput | Prisma.NalogaCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NalogaIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Naloga update
 */
export type NalogaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Naloga
   */
  select?: Prisma.NalogaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Naloga
   */
  omit?: Prisma.NalogaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NalogaInclude<ExtArgs> | null
  /**
   * The data needed to update a Naloga.
   */
  data: Prisma.XOR<Prisma.NalogaUpdateInput, Prisma.NalogaUncheckedUpdateInput>
  /**
   * Choose, which Naloga to update.
   */
  where: Prisma.NalogaWhereUniqueInput
}

/**
 * Naloga updateMany
 */
export type NalogaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Nalogas.
   */
  data: Prisma.XOR<Prisma.NalogaUpdateManyMutationInput, Prisma.NalogaUncheckedUpdateManyInput>
  /**
   * Filter which Nalogas to update
   */
  where?: Prisma.NalogaWhereInput
  /**
   * Limit how many Nalogas to update.
   */
  limit?: number
}

/**
 * Naloga updateManyAndReturn
 */
export type NalogaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Naloga
   */
  select?: Prisma.NalogaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Naloga
   */
  omit?: Prisma.NalogaOmit<ExtArgs> | null
  /**
   * The data used to update Nalogas.
   */
  data: Prisma.XOR<Prisma.NalogaUpdateManyMutationInput, Prisma.NalogaUncheckedUpdateManyInput>
  /**
   * Filter which Nalogas to update
   */
  where?: Prisma.NalogaWhereInput
  /**
   * Limit how many Nalogas to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NalogaIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Naloga upsert
 */
export type NalogaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Naloga
   */
  select?: Prisma.NalogaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Naloga
   */
  omit?: Prisma.NalogaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NalogaInclude<ExtArgs> | null
  /**
   * The filter to search for the Naloga to update in case it exists.
   */
  where: Prisma.NalogaWhereUniqueInput
  /**
   * In case the Naloga found by the `where` argument doesn't exist, create a new Naloga with this data.
   */
  create: Prisma.XOR<Prisma.NalogaCreateInput, Prisma.NalogaUncheckedCreateInput>
  /**
   * In case the Naloga was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NalogaUpdateInput, Prisma.NalogaUncheckedUpdateInput>
}

/**
 * Naloga delete
 */
export type NalogaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Naloga
   */
  select?: Prisma.NalogaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Naloga
   */
  omit?: Prisma.NalogaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NalogaInclude<ExtArgs> | null
  /**
   * Filter which Naloga to delete.
   */
  where: Prisma.NalogaWhereUniqueInput
}

/**
 * Naloga deleteMany
 */
export type NalogaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Nalogas to delete
   */
  where?: Prisma.NalogaWhereInput
  /**
   * Limit how many Nalogas to delete.
   */
  limit?: number
}

/**
 * Naloga without action
 */
export type NalogaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Naloga
   */
  select?: Prisma.NalogaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Naloga
   */
  omit?: Prisma.NalogaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NalogaInclude<ExtArgs> | null
}
